''' Questions Database '''

english = [
    {'question_string' : 'My friends ______ groundnuts daily.', 
'options' : ['eating', 'are eat', 'eats', 'eat', 'was eat', ],
'correct_option' : 'eat',
'topics' : ['happens',]},
{'question_string' : 'You ______ every weekend.', 
'options' : ['was swim', 'are swim', 'swim', 'swims', 'swimming', ],
'correct_option' : 'swim',
'topics' : ['happens',]},
{'question_string' : 'The boy ______ from time to time.', 
'options' : ['sleeps', 'is sleep', 'sleeping', 'is sleeps', 'sleep', ],
'correct_option' : 'sleeps',
'topics' : ['happens',]},
{'question_string' : 'You ______ every Wednesday.', 
'options' : ['works', 'working', 'work', 'are work', 'was work', ],
'correct_option' : 'work',
'topics' : ['happens',]},
{'question_string' : 'He ______ from time to time.', 
'options' : ['is speaks', 'speaking', 'speaks', 'speak', 'is speak', ],
'correct_option' : 'speaks',
'topics' : ['happens',]},
{'question_string' : 'I ______ again and again.', 
'options' : ['am work', 'was work', 'works', 'work', 'working', ],
'correct_option' : 'work',
'topics' : ['happens',]},
{'question_string' : 'I ______ every time.', 
'options' : ['sing', 'am sing', 'singing', 'sings', 'was sing', ],
'correct_option' : 'sing',
'topics' : ['happens',]},
{'question_string' : 'Both of you ______ every Saturday.', 
'options' : ['speaking', 'speak', 'was speak', 'speaks', 'are speak', ],
'correct_option' : 'speak',
'topics' : ['happens',]},
{'question_string' : 'She ______ every time.', 
'options' : ['sings', 'is sings', 'singing', 'is sing', 'sing', ],
'correct_option' : 'sings',
'topics' : ['happens',]},
{'question_string' : 'My parents ______ every time.', 
'options' : ['speak', 'was speak', 'speaking', 'are speak', 'speaks', ],
'correct_option' : 'speak',
'topics' : ['happens',]},
{'question_string' : 'All of us ______ yam again and again.', 
'options' : ['eats', 'was eat', 'eat', 'eating', 'are eat', ],
'correct_option' : 'eat',
'topics' : ['happens',]},
{'question_string' : 'You ______ bread every time.', 
'options' : ['eating', 'eats', 'are eat', 'was eat', 'eat', ],
'correct_option' : 'eat',
'topics' : ['happens',]},
{'question_string' : 'You ______ every now and then.', 
'options' : ['drinking', 'was drink', 'drink', 'are drink', 'drinks', ],
'correct_option' : 'drink',
'topics' : ['happens',]},
{'question_string' : 'I ______ every time.', 
'options' : ['drink', 'drinking', 'am drink', 'was drink', 'drinks', ],
'correct_option' : 'drink',
'topics' : ['happens',]},
{'question_string' : 'They ______ from time to time.', 
'options' : ['are speak', 'speaks', 'was speak', 'speak', 'speaking', ],
'correct_option' : 'speak',
'topics' : ['happens',]},
{'question_string' : 'She ______ all the time.', 
'options' : ['speaks', 'speaking', 'speak', 'is speaks', 'is speak', ],
'correct_option' : 'speaks',
'topics' : ['happens',]},
{'question_string' : 'Both of you ______ every Saturday.', 
'options' : ['drinking', 'was drink', 'are drink', 'drinks', 'drink', ],
'correct_option' : 'drink',
'topics' : ['happens',]},
{'question_string' : 'They ______ often.', 
'options' : ['are work', 'works', 'was work', 'work', 'working', ],
'correct_option' : 'work',
'topics' : ['happens',]},
{'question_string' : 'Many of you ______ frequently.', 
'options' : ['drink', 'drinks', 'drinking', 'was drink', 'are drink', ],
'correct_option' : 'drink',
'topics' : ['happens',]},
{'question_string' : 'They ______ usually.', 
'options' : ['was drink', 'drink', 'are drink', 'drinks', 'drinking', ],
'correct_option' : 'drink',
'topics' : ['happens',]},
{'question_string' : 'I ______ usually.', 
'options' : ['drinks', 'was drink', 'drink', 'am drink', 'drinking', ],
'correct_option' : 'drink',
'topics' : ['happens',]},
{'question_string' : 'My friend ______ all the time.', 
'options' : ['is swim', 'is swims', 'swims', 'swim', 'swimming', ],
'correct_option' : 'swims',
'topics' : ['happens',]},
{'question_string' : 'That child ______ from time to time.', 
'options' : ['working', 'is works', 'work', 'works', 'is work', ],
'correct_option' : 'works',
'topics' : ['happens',]},
{'question_string' : 'I ______ repeatedly.', 
'options' : ['am work', 'working', 'work', 'was work', 'works', ],
'correct_option' : 'work',
'topics' : ['happens',]},
{'question_string' : 'Many of you ______ frequently.', 
'options' : ['are drink', 'drink', 'drinking', 'was drink', 'drinks', ],
'correct_option' : 'drink',
'topics' : ['happens',]},
{'question_string' : 'My friend ______ a few times this month.', 
'options' : ['have spoken', 'has speak', 'has spoken', 'is spoke', 'was spoke', ],
'correct_option' : 'has spoken',
'topics' : ['has happened',]},
{'question_string' : 'The boy ______ several times this year.', 
'options' : ['was sang', 'have sung', 'is sang', 'has sung', 'has sing', ],
'correct_option' : 'has sung',
'topics' : ['has happened',]},
{'question_string' : 'He ______ several times this year.', 
'options' : ['have sung', 'has sing', 'was sang', 'has sung', 'is sang', ],
'correct_option' : 'has sung',
'topics' : ['has happened',]},
{'question_string' : 'Some of you ______ already.', 
'options' : ['have swum', 'are swam', 'were swam', 'has swum', 'have swim', ],
'correct_option' : 'have swum',
'topics' : ['has happened',]},
{'question_string' : 'I ______ many times this week.', 
'options' : ['has drunk', 'have drunk', 'was drank', 'am drank', 'have drink', ],
'correct_option' : 'have drunk',
'topics' : ['has happened',]},
{'question_string' : 'The girl ______ several times this year.', 
'options' : ['was slept', 'has slept', 'has sleep', 'is slept', 'have slept', ],
'correct_option' : 'has slept',
'topics' : ['has happened',]},
{'question_string' : 'Both of us ______ several times this year.', 
'options' : ['were drank', 'are drank', 'has drunk', 'have drink', 'have drunk', ],
'correct_option' : 'have drunk',
'topics' : ['has happened',]},
{'question_string' : 'She ______ today.', 
'options' : ['is ate', 'has eaten', 'have eaten', 'has eat', 'was ate', ],
'correct_option' : 'has eaten',
'topics' : ['has happened',]},
{'question_string' : 'They ______ several times this year.', 
'options' : ['are slept', 'has slept', 'have sleep', 'were slept', 'have slept', ],
'correct_option' : 'have slept',
'topics' : ['has happened',]},
{'question_string' : 'All of us ______ many times this week.', 
'options' : ['were sang', 'are sang', 'has sung', 'have sung', 'have sing', ],
'correct_option' : 'have sung',
'topics' : ['has happened',]},
{'question_string' : 'The boy ______ today.', 
'options' : ['has slept', 'have slept', 'has sleep', 'is slept', 'was slept', ],
'correct_option' : 'has slept',
'topics' : ['has happened',]},
{'question_string' : 'You ______ already.', 
'options' : ['have sleep', 'have slept', 'were slept', 'are slept', 'has slept', ],
'correct_option' : 'have slept',
'topics' : ['has happened',]},
{'question_string' : 'That child ______ a few times this month.', 
'options' : ['have eaten', 'is ate', 'has eat', 'has eaten', 'was ate', ],
'correct_option' : 'has eaten',
'topics' : ['has happened',]},
{'question_string' : 'I ______ several times this year.', 
'options' : ['am worked', 'has worked', 'was worked', 'have work', 'have worked', ],
'correct_option' : 'have worked',
'topics' : ['has happened',]},
{'question_string' : 'The girl ______ today.', 
'options' : ['is sang', 'was sang', 'has sing', 'has sung', 'have sung', ],
'correct_option' : 'has sung',
'topics' : ['has happened',]},
{'question_string' : 'He ______ today.', 
'options' : ['has spoken', 'was spoke', 'has speak', 'is spoke', 'have spoken', ],
'correct_option' : 'has spoken',
'topics' : ['has happened',]},
{'question_string' : 'Both of you ______ already.', 
'options' : ['have slept', 'were slept', 'has slept', 'are slept', 'have sleep', ],
'correct_option' : 'have slept',
'topics' : ['has happened',]},
{'question_string' : 'You ______ already.', 
'options' : ['have drunk', 'have drink', 'has drunk', 'were drank', 'are drank', ],
'correct_option' : 'have drunk',
'topics' : ['has happened',]},
{'question_string' : 'I ______ a few times this month.', 
'options' : ['was worked', 'am worked', 'have work', 'has worked', 'have worked', ],
'correct_option' : 'have worked',
'topics' : ['has happened',]},
{'question_string' : 'He ______ many times this week.', 
'options' : ['has swum', 'is swam', 'was swam', 'has swim', 'have swum', ],
'correct_option' : 'has swum',
'topics' : ['has happened',]},
{'question_string' : 'My parents ______ many times this week.', 
'options' : ['has spoken', 'have spoken', 'were spoke', 'have speak', 'are spoke', ],
'correct_option' : 'have spoken',
'topics' : ['has happened',]},
{'question_string' : 'He ______ many times this week.', 
'options' : ['has drink', 'was drank', 'have drunk', 'has drunk', 'is drank', ],
'correct_option' : 'has drunk',
'topics' : ['has happened',]},
{'question_string' : 'He ______ a few times this month.', 
'options' : ['have worked', 'is worked', 'has work', 'has worked', 'was worked', ],
'correct_option' : 'has worked',
'topics' : ['has happened',]},
{'question_string' : 'He ______ today.', 
'options' : ['has sleep', 'was slept', 'has slept', 'is slept', 'have slept', ],
'correct_option' : 'has slept',
'topics' : ['has happened',]},
{'question_string' : 'That child ______ many times this week.', 
'options' : ['was ate', 'have eaten', 'is ate', 'has eat', 'has eaten', ],
'correct_option' : 'has eaten',
'topics' : ['has happened',]},
{'question_string' : 'My friend ______ happy earlier today.', 
'options' : ['were', 'are', 'am', 'is', 'was', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'The girl ______ happy last night.', 
'options' : ['was', 'is', 'am', 'were', 'are', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'The girl ______ excited three hours ago.', 
'options' : ['was', 'is', 'are', 'were', 'am', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'My friends ______ sick three hours ago.', 
'options' : ['am', 'is', 'are', 'was', 'were', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'They ______ excited yesterday.', 
'options' : ['was', 'are', 'were', 'am', 'is', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'I ______ cheerful two hours ago.', 
'options' : ['is', 'are', 'was', 'am', 'were', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'The boy ______ angry at this moment.', 
'options' : ['was', 'were', 'am', 'is', 'are', ],
'correct_option' : 'is',
'topics' : ['is so',]},
{'question_string' : 'You ______ excited three hours ago.', 
'options' : ['were', 'was', 'is', 'am', 'are', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'I ______ quiet as we speak.', 
'options' : ['are', 'were', 'am', 'was', 'is', ],
'correct_option' : 'am',
'topics' : ['is so',]},
{'question_string' : 'Both of you ______ happy two days ago.', 
'options' : ['were', 'is', 'am', 'was', 'are', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'She ______ quiet before now.', 
'options' : ['were', 'am', 'are', 'is', 'was', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'Many of you ______ angry yesterday.', 
'options' : ['is', 'are', 'am', 'was', 'were', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'I ______ cheerful three hours ago.', 
'options' : ['was', 'were', 'are', 'is', 'am', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'All of us ______ cheerful at this very moment.', 
'options' : ['was', 'were', 'is', 'am', 'are', ],
'correct_option' : 'are',
'topics' : ['is so',]},
{'question_string' : 'You ______ happy one hour ago.', 
'options' : ['was', 'is', 'am', 'were', 'are', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'She ______ sick two hours ago.', 
'options' : ['was', 'were', 'am', 'is', 'are', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'Our children ______ angry one hour ago.', 
'options' : ['is', 'am', 'are', 'were', 'was', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'You ______ excited two days ago.', 
'options' : ['is', 'were', 'are', 'am', 'was', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'You ______ quiet yesterday.', 
'options' : ['was', 'were', 'am', 'is', 'are', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'She ______ excited earlier today.', 
'options' : ['was', 'were', 'are', 'is', 'am', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'The students ______ excited before now.', 
'options' : ['am', 'is', 'was', 'were', 'are', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'My friend ______ angry last night.', 
'options' : ['is', 'was', 'are', 'were', 'am', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'You ______ sick the day before yesterday.', 
'options' : ['was', 'is', 'are', 'were', 'am', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'You ______ excited the day before yesterday.', 
'options' : ['am', 'were', 'are', 'is', 'was', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'I ______ quiet the day before yesterday.', 
'options' : ['are', 'am', 'was', 'were', 'is', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'My parents ______ traders three months ago.', 
'options' : ['are', 'were', 'is', 'was', 'am', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'Our children ______ dancers last year.', 
'options' : ['are', 'was', 'am', 'is', 'were', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'You ______ a teacher three months ago.', 
'options' : ['was', 'am', 'is', 'were', 'are', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'Our children ______ architects last month.', 
'options' : ['are', 'was', 'were', 'am', 'is', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'We ______ students at this time.', 
'options' : ['were', 'are', 'was', 'is', 'am', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'All of us ______ musicians at present.', 
'options' : ['are', 'were', 'was', 'am', 'is', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'I ______ an agent at present.', 
'options' : ['is', 'are', 'was', 'were', 'am', ],
'correct_option' : 'am',
'topics' : ['is something',]},
{'question_string' : 'Some of us ______ teachers at this time.', 
'options' : ['are', 'was', 'am', 'were', 'is', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'She ______ an artist for now.', 
'options' : ['was', 'am', 'were', 'is', 'are', ],
'correct_option' : 'is',
'topics' : ['is something',]},
{'question_string' : 'The girl ______ a teacher before now.', 
'options' : ['am', 'were', 'are', 'is', 'was', ],
'correct_option' : 'was',
'topics' : ['is something',]},
{'question_string' : 'You ______ an artist for now.', 
'options' : ['was', 'are', 'were', 'is', 'am', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'The girl ______ a teacher for now.', 
'options' : ['was', 'am', 'are', 'were', 'is', ],
'correct_option' : 'is',
'topics' : ['is something',]},
{'question_string' : 'All of us ______ drivers last year.', 
'options' : ['am', 'was', 'were', 'is', 'are', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'I ______ a trader for now.', 
'options' : ['was', 'were', 'is', 'are', 'am', ],
'correct_option' : 'am',
'topics' : ['is something',]},
{'question_string' : 'My parents ______ dancers last month.', 
'options' : ['am', 'were', 'is', 'are', 'was', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'My friends ______ students before now.', 
'options' : ['was', 'were', 'are', 'am', 'is', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'I ______ an electrician for now.', 
'options' : ['was', 'were', 'are', 'am', 'is', ],
'correct_option' : 'am',
'topics' : ['is something',]},
{'question_string' : 'You ______ a trader at present.', 
'options' : ['were', 'are', 'was', 'is', 'am', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'The boy ______ a trader last month.', 
'options' : ['was', 'were', 'am', 'are', 'is', ],
'correct_option' : 'was',
'topics' : ['is something',]},
{'question_string' : 'Our children ______ artists at present.', 
'options' : ['is', 'are', 'am', 'were', 'was', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'My friend ______ a trader last month.', 
'options' : ['were', 'is', 'am', 'was', 'are', ],
'correct_option' : 'was',
'topics' : ['is something',]},
{'question_string' : 'I ______ an artist last month.', 
'options' : ['is', 'are', 'am', 'were', 'was', ],
'correct_option' : 'was',
'topics' : ['is something',]},
{'question_string' : 'I ______ an accountant three months ago.', 
'options' : ['were', 'is', 'was', 'am', 'are', ],
'correct_option' : 'was',
'topics' : ['is something',]},
{'question_string' : 'Many of you ______ interpreters last year.', 
'options' : ['am', 'are', 'is', 'were', 'was', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'My parents ______ agents at this time.', 
'options' : ['are', 'were', 'was', 'am', 'is', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'I ______ every now and then.', 
'options' : ['sleeps', 'was sleep', 'sleeping', 'am sleep', 'sleep', ],
'correct_option' : 'sleep',
'topics' : ['happens',]},
{'question_string' : 'I ______ repeatedly.', 
'options' : ['singing', 'sings', 'sing', 'am sing', 'was sing', ],
'correct_option' : 'sing',
'topics' : ['happens',]},
{'question_string' : 'We ______ from time to time.', 
'options' : ['was swim', 'are swim', 'swims', 'swim', 'swimming', ],
'correct_option' : 'swim',
'topics' : ['happens',]},
{'question_string' : 'Some of us ______ daily.', 
'options' : ['are speak', 'speaking', 'speak', 'speaks', 'was speak', ],
'correct_option' : 'speak',
'topics' : ['happens',]},
{'question_string' : 'She ______ again and again.', 
'options' : ['swims', 'swim', 'is swim', 'swimming', 'is swims', ],
'correct_option' : 'swims',
'topics' : ['happens',]},
{'question_string' : 'Both of us ______ often.', 
'options' : ['sings', 'are sing', 'singing', 'was sing', 'sing', ],
'correct_option' : 'sing',
'topics' : ['happens',]},
{'question_string' : 'I ______ every week.', 
'options' : ['sing', 'am sing', 'sings', 'was sing', 'singing', ],
'correct_option' : 'sing',
'topics' : ['happens',]},
{'question_string' : 'All of us ______ daily.', 
'options' : ['are sing', 'sing', 'sings', 'singing', 'was sing', ],
'correct_option' : 'sing',
'topics' : ['happens',]},
{'question_string' : 'You ______ every time.', 
'options' : ['work', 'was work', 'are work', 'works', 'working', ],
'correct_option' : 'work',
'topics' : ['happens',]},
{'question_string' : 'Both of us ______ frequently.', 
'options' : ['sings', 'are sing', 'sing', 'singing', 'was sing', ],
'correct_option' : 'sing',
'topics' : ['happens',]},
{'question_string' : 'I ______ again and again.', 
'options' : ['singing', 'was sing', 'sing', 'am sing', 'sings', ],
'correct_option' : 'sing',
'topics' : ['happens',]},
{'question_string' : 'Some of us ______ again and again.', 
'options' : ['sing', 'are sing', 'sings', 'was sing', 'singing', ],
'correct_option' : 'sing',
'topics' : ['happens',]},
{'question_string' : 'My friend ______ every week.', 
'options' : ['works', 'working', 'is works', 'work', 'is work', ],
'correct_option' : 'works',
'topics' : ['happens',]},
{'question_string' : 'He ______ every weekend.', 
'options' : ['speaks', 'speak', 'speaking', 'is speak', 'is speaks', ],
'correct_option' : 'speaks',
'topics' : ['happens',]},
{'question_string' : 'That child ______ every week.', 
'options' : ['sleeping', 'is sleeps', 'is sleep', 'sleep', 'sleeps', ],
'correct_option' : 'sleeps',
'topics' : ['happens',]},
{'question_string' : 'My friend and I ______ usually.', 
'options' : ['swimming', 'are swim', 'swim', 'swims', 'was swim', ],
'correct_option' : 'swim',
'topics' : ['happens',]},
{'question_string' : 'Many of you ______ on weekends.', 
'options' : ['working', 'works', 'was work', 'are work', 'work', ],
'correct_option' : 'work',
'topics' : ['happens',]},
{'question_string' : 'He ______ from time to time.', 
'options' : ['sleeps', 'is sleep', 'sleep', 'sleeping', 'is sleeps', ],
'correct_option' : 'sleeps',
'topics' : ['happens',]},
{'question_string' : 'Many of you ______ from time to time.', 
'options' : ['was swim', 'are swim', 'swimming', 'swims', 'swim', ],
'correct_option' : 'swim',
'topics' : ['happens',]},
{'question_string' : 'My friends ______ on Mondays.', 
'options' : ['are sing', 'was sing', 'sings', 'singing', 'sing', ],
'correct_option' : 'sing',
'topics' : ['happens',]},
{'question_string' : 'My friend and I ______ every now and then.', 
'options' : ['are sing', 'sing', 'sings', 'was sing', 'singing', ],
'correct_option' : 'sing',
'topics' : ['happens',]},
{'question_string' : 'That child ______ on Sundays.', 
'options' : ['speak', 'is speaks', 'speaking', 'is speak', 'speaks', ],
'correct_option' : 'speaks',
'topics' : ['happens',]},
{'question_string' : 'You ______ every weekend.', 
'options' : ['are swim', 'was swim', 'swim', 'swims', 'swimming', ],
'correct_option' : 'swim',
'topics' : ['happens',]},
{'question_string' : 'She ______ on weekends.', 
'options' : ['is drink', 'drinking', 'drinks', 'is drinks', 'drink', ],
'correct_option' : 'drinks',
'topics' : ['happens',]},
{'question_string' : 'You ______ popcorn daily.', 
'options' : ['eats', 'eating', 'are eat', 'eat', 'was eat', ],
'correct_option' : 'eat',
'topics' : ['happens',]},
{'question_string' : 'My friend ______ many times this week.', 
'options' : ['is sang', 'was sang', 'has sung', 'have sung', 'has sing', ],
'correct_option' : 'has sung',
'topics' : ['has happened',]},
{'question_string' : 'The girl ______ a few times this month.', 
'options' : ['has worked', 'was worked', 'has work', 'have worked', 'is worked', ],
'correct_option' : 'has worked',
'topics' : ['has happened',]},
{'question_string' : 'Many of you ______ already.', 
'options' : ['were ate', 'are ate', 'have eaten', 'have eat', 'has eaten', ],
'correct_option' : 'have eaten',
'topics' : ['has happened',]},
{'question_string' : 'I ______ a few times this month.', 
'options' : ['was worked', 'am worked', 'have work', 'have worked', 'has worked', ],
'correct_option' : 'have worked',
'topics' : ['has happened',]},
{'question_string' : 'We ______ already.', 
'options' : ['have eaten', 'has eaten', 'are ate', 'were ate', 'have eat', ],
'correct_option' : 'have eaten',
'topics' : ['has happened',]},
{'question_string' : 'I ______ today.', 
'options' : ['have speak', 'was spoke', 'have spoken', 'has spoken', 'am spoke', ],
'correct_option' : 'have spoken',
'topics' : ['has happened',]},
{'question_string' : 'She ______ already.', 
'options' : ['has swum', 'was swam', 'has swim', 'is swam', 'have swum', ],
'correct_option' : 'has swum',
'topics' : ['has happened',]},
{'question_string' : 'All of you ______ today.', 
'options' : ['are spoke', 'have spoken', 'has spoken', 'have speak', 'were spoke', ],
'correct_option' : 'have spoken',
'topics' : ['has happened',]},
{'question_string' : 'Both of us ______ several times this year.', 
'options' : ['have work', 'has worked', 'are worked', 'have worked', 'were worked', ],
'correct_option' : 'have worked',
'topics' : ['has happened',]},
{'question_string' : 'My friends ______ several times this year.', 
'options' : ['were drank', 'have drunk', 'are drank', 'has drunk', 'have drink', ],
'correct_option' : 'have drunk',
'topics' : ['has happened',]},
{'question_string' : 'We ______ many times this week.', 
'options' : ['have swum', 'are swam', 'were swam', 'has swum', 'have swim', ],
'correct_option' : 'have swum',
'topics' : ['has happened',]},
{'question_string' : 'Both of you ______ several times this year.', 
'options' : ['have worked', 'are worked', 'were worked', 'have work', 'has worked', ],
'correct_option' : 'have worked',
'topics' : ['has happened',]},
{'question_string' : 'The boy ______ already.', 
'options' : ['has drink', 'has drunk', 'was drank', 'have drunk', 'is drank', ],
'correct_option' : 'has drunk',
'topics' : ['has happened',]},
{'question_string' : 'You ______ several times this year.', 
'options' : ['has worked', 'are worked', 'were worked', 'have worked', 'have work', ],
'correct_option' : 'have worked',
'topics' : ['has happened',]},
{'question_string' : 'Some of us ______ already.', 
'options' : ['are ate', 'has eaten', 'have eaten', 'have eat', 'were ate', ],
'correct_option' : 'have eaten',
'topics' : ['has happened',]},
{'question_string' : 'He ______ several times this year.', 
'options' : ['have swum', 'has swim', 'was swam', 'is swam', 'has swum', ],
'correct_option' : 'has swum',
'topics' : ['has happened',]},
{'question_string' : 'You ______ many times this week.', 
'options' : ['have swum', 'are swam', 'have swim', 'were swam', 'has swum', ],
'correct_option' : 'have swum',
'topics' : ['has happened',]},
{'question_string' : 'He ______ today.', 
'options' : ['is swam', 'have swum', 'has swum', 'was swam', 'has swim', ],
'correct_option' : 'has swum',
'topics' : ['has happened',]},
{'question_string' : 'You ______ today.', 
'options' : ['have eaten', 'have eat', 'are ate', 'were ate', 'has eaten', ],
'correct_option' : 'have eaten',
'topics' : ['has happened',]},
{'question_string' : 'You ______ several times this year.', 
'options' : ['are worked', 'have work', 'has worked', 'were worked', 'have worked', ],
'correct_option' : 'have worked',
'topics' : ['has happened',]},
{'question_string' : 'Many of you ______ already.', 
'options' : ['has worked', 'were worked', 'are worked', 'have worked', 'have work', ],
'correct_option' : 'have worked',
'topics' : ['has happened',]},
{'question_string' : 'You ______ today.', 
'options' : ['were worked', 'have worked', 'have work', 'has worked', 'are worked', ],
'correct_option' : 'have worked',
'topics' : ['has happened',]},
{'question_string' : 'We ______ already.', 
'options' : ['have eaten', 'were ate', 'are ate', 'have eat', 'has eaten', ],
'correct_option' : 'have eaten',
'topics' : ['has happened',]},
{'question_string' : 'He ______ today.', 
'options' : ['is drank', 'was drank', 'have drunk', 'has drunk', 'has drink', ],
'correct_option' : 'has drunk',
'topics' : ['has happened',]},
{'question_string' : 'All of you ______ many times this week.', 
'options' : ['has eaten', 'are ate', 'have eat', 'were ate', 'have eaten', ],
'correct_option' : 'have eaten',
'topics' : ['has happened',]},
{'question_string' : 'Both of you ______ sick two days ago.', 
'options' : ['were', 'was', 'am', 'is', 'are', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'I ______ sick last weekend.', 
'options' : ['was', 'am', 'are', 'is', 'were', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'You ______ quiet at this very moment.', 
'options' : ['were', 'was', 'am', 'is', 'are', ],
'correct_option' : 'are',
'topics' : ['is so',]},
{'question_string' : 'You ______ cheerful as we speak.', 
'options' : ['were', 'was', 'is', 'am', 'are', ],
'correct_option' : 'are',
'topics' : ['is so',]},
{'question_string' : 'Both of us ______ happy right now.', 
'options' : ['was', 'is', 'are', 'am', 'were', ],
'correct_option' : 'are',
'topics' : ['is so',]},
{'question_string' : 'That child ______ quiet two weeks ago.', 
'options' : ['are', 'was', 'is', 'am', 'were', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'He ______ excited last night.', 
'options' : ['am', 'were', 'are', 'was', 'is', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'My friends ______ quiet last night.', 
'options' : ['were', 'is', 'was', 'am', 'are', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'All of us ______ excited as we speak.', 
'options' : ['is', 'are', 'am', 'was', 'were', ],
'correct_option' : 'are',
'topics' : ['is so',]},
{'question_string' : 'Both of you ______ cheerful the day before yesterday.', 
'options' : ['was', 'are', 'am', 'is', 'were', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'Our children ______ happy three hours ago.', 
'options' : ['were', 'was', 'are', 'is', 'am', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'I ______ angry two days ago.', 
'options' : ['were', 'is', 'was', 'are', 'am', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'You ______ cheerful two hours ago.', 
'options' : ['is', 'were', 'are', 'was', 'am', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'Our children ______ cheerful earlier today.', 
'options' : ['is', 'was', 'were', 'am', 'are', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'They ______ cheerful before now.', 
'options' : ['am', 'were', 'was', 'is', 'are', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'Some of us ______ excited two days ago.', 
'options' : ['were', 'am', 'is', 'was', 'are', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'My friend ______ angry three hours ago.', 
'options' : ['were', 'are', 'am', 'was', 'is', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'My friend and I ______ sick two days ago.', 
'options' : ['am', 'was', 'are', 'were', 'is', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'The boy ______ angry at this moment.', 
'options' : ['was', 'were', 'is', 'are', 'am', ],
'correct_option' : 'is',
'topics' : ['is so',]},
{'question_string' : 'I ______ angry three days ago.', 
'options' : ['were', 'am', 'is', 'are', 'was', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'She ______ happy last weekend.', 
'options' : ['was', 'am', 'were', 'is', 'are', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'I ______ happy three days ago.', 
'options' : ['is', 'were', 'am', 'was', 'are', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'My parents ______ quiet right now.', 
'options' : ['was', 'is', 'am', 'were', 'are', ],
'correct_option' : 'are',
'topics' : ['is so',]},
{'question_string' : 'You and I ______ sick before now.', 
'options' : ['is', 'was', 'were', 'are', 'am', ],
'correct_option' : 'were',
'topics' : ['is so',]},
{'question_string' : 'I ______ quiet two days ago.', 
'options' : ['am', 'is', 'are', 'was', 'were', ],
'correct_option' : 'was',
'topics' : ['is so',]},
{'question_string' : 'I ______ an electrician for now.', 
'options' : ['are', 'was', 'is', 'were', 'am', ],
'correct_option' : 'am',
'topics' : ['is something',]},
{'question_string' : 'We ______ politicians before now.', 
'options' : ['am', 'are', 'is', 'was', 'were', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'She ______ a musician at this time.', 
'options' : ['were', 'was', 'am', 'is', 'are', ],
'correct_option' : 'is',
'topics' : ['is something',]},
{'question_string' : 'Our children ______ accountants at this time.', 
'options' : ['are', 'is', 'was', 'were', 'am', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'You ______ a trader before now.', 
'options' : ['were', 'am', 'is', 'are', 'was', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'Both of you ______ interpreters last month.', 
'options' : ['was', 'were', 'are', 'is', 'am', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'You ______ an architect now.', 
'options' : ['am', 'were', 'is', 'are', 'was', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'All of us ______ accountants before now.', 
'options' : ['were', 'are', 'is', 'am', 'was', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'My friend and I ______ artists last month.', 
'options' : ['are', 'is', 'was', 'were', 'am', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'Some of us ______ electricians three months ago.', 
'options' : ['was', 'am', 'were', 'is', 'are', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'I ______ a student for now.', 
'options' : ['am', 'is', 'was', 'are', 'were', ],
'correct_option' : 'am',
'topics' : ['is something',]},
{'question_string' : 'You ______ a driver at this time.', 
'options' : ['are', 'was', 'am', 'is', 'were', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'My friend ______ a student last month.', 
'options' : ['was', 'were', 'is', 'am', 'are', ],
'correct_option' : 'was',
'topics' : ['is something',]},
{'question_string' : 'The students ______ teachers now.', 
'options' : ['is', 'was', 'were', 'are', 'am', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'The boy ______ an electrician at this time.', 
'options' : ['is', 'am', 'was', 'were', 'are', ],
'correct_option' : 'is',
'topics' : ['is something',]},
{'question_string' : 'You ______ architects at this time.', 
'options' : ['is', 'am', 'was', 'are', 'were', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'My friend and I ______ teachers now.', 
'options' : ['were', 'is', 'was', 'are', 'am', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'You ______ a trader three months ago.', 
'options' : ['am', 'is', 'are', 'was', 'were', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'I ______ a student before now.', 
'options' : ['was', 'am', 'are', 'were', 'is', ],
'correct_option' : 'was',
'topics' : ['is something',]},
{'question_string' : 'I ______ a teacher last month.', 
'options' : ['are', 'was', 'is', 'were', 'am', ],
'correct_option' : 'was',
'topics' : ['is something',]},
{'question_string' : 'Many of you ______ interpreters at present.', 
'options' : ['were', 'am', 'is', 'are', 'was', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'My parents ______ students at this time.', 
'options' : ['was', 'am', 'is', 'were', 'are', ],
'correct_option' : 'are',
'topics' : ['is something',]},
{'question_string' : 'My friends ______ teachers before now.', 
'options' : ['am', 'is', 'was', 'are', 'were', ],
'correct_option' : 'were',
'topics' : ['is something',]},
{'question_string' : 'That child ______ a musician before now.', 
'options' : ['was', 'were', 'am', 'is', 'are', ],
'correct_option' : 'was',
'topics' : ['is something',]},
{'question_string' : 'I ______ a dancer before now.', 
'options' : ['is', 'are', 'was', 'were', 'am', ],
'correct_option' : 'was',
'topics' : ['is something',]},
{'question_string' : 'My friend ______ again and again, I am sure.', 
'options' : ['was not drinks', 'is not drink', 'do drink', 'does drink', 'are not drinking', ],
'correct_option' : 'does drink',
'topics' : ['does happen',]},
{'question_string' : 'My friends ______ on Sundays, I am sure.', 
'options' : ['do sing', 'does sing', 'are not sing', 'was not singing', 'was not sing', ],
'correct_option' : 'do sing',
'topics' : ['does happen',]},
{'question_string' : 'Our children ______ again and again, I am sure.', 
'options' : ['does swim', 'was not swimming', 'are not swim', 'was not swim', 'do swim', ],
'correct_option' : 'do swim',
'topics' : ['does happen',]},
{'question_string' : 'All of you ______ every Wednesday, I am sure.', 
'options' : ['does speak', 'was not speak', 'do speak', 'was not speaking', 'are not speak', ],
'correct_option' : 'do speak',
'topics' : ['does happen',]},
{'question_string' : 'I ______ on Sundays, I am sure.', 
'options' : ['am not work', 'are not working', 'do work', 'was not work', 'does work', ],
'correct_option' : 'do work',
'topics' : ['does happen',]},
{'question_string' : 'You ______ on Mondays, I am sure.', 
'options' : ['are not sing', 'do sing', 'was not singing', 'was not sing', 'does sing', ],
'correct_option' : 'do sing',
'topics' : ['does happen',]},
{'question_string' : 'My friend and I ______ popcorn again and again, I am sure.', 
'options' : ['was not eat', 'does eat', 'was not eating', 'are not eat', 'do eat', ],
'correct_option' : 'do eat',
'topics' : ['does happen',]},
{'question_string' : 'That child ______ bread from time to time, I am sure.', 
'options' : ['does eat', 'is not eat', 'are not eating', 'was not eats', 'do eat', ],
'correct_option' : 'does eat',
'topics' : ['does happen',]},
{'question_string' : 'You ______ every weekend, I am sure.', 
'options' : ['do drink', 'was not drink', 'are not drink', 'does drink', 'was not drinking', ],
'correct_option' : 'do drink',
'topics' : ['does happen',]},
{'question_string' : 'I ______ every Wednesday, I am sure.', 
'options' : ['are not working', 'am not work', 'do work', 'does work', 'was not work', ],
'correct_option' : 'do work',
'topics' : ['does happen',]},
{'question_string' : 'Many of you ______ every weekend, I am sure.', 
'options' : ['are not sleep', 'was not sleeping', 'was not sleep', 'does sleep', 'do sleep', ],
'correct_option' : 'do sleep',
'topics' : ['does happen',]},
{'question_string' : 'I ______ every week, I am sure.', 
'options' : ['am not speak', 'are not speaking', 'does speak', 'do speak', 'was not speak', ],
'correct_option' : 'do speak',
'topics' : ['does happen',]},
{'question_string' : 'My friend ______ on Mondays, I am sure.', 
'options' : ['do swim', 'are not swimming', 'does swim', 'was not swims', 'is not swim', ],
'correct_option' : 'does swim',
'topics' : ['does happen',]},
{'question_string' : 'Many of you ______ bread on weekends, I am sure.', 
'options' : ['was not eating', 'was not eat', 'does eat', 'are not eat', 'do eat', ],
'correct_option' : 'do eat',
'topics' : ['does happen',]},
{'question_string' : 'You ______ on weekends, I am sure.', 
'options' : ['was not sleeping', 'are not sleep', 'was not sleep', 'do sleep', 'does sleep', ],
'correct_option' : 'do sleep',
'topics' : ['does happen',]},
{'question_string' : 'Some of you ______ again and again, I am sure.', 
'options' : ['does swim', 'was not swimming', 'was not swim', 'are not swim', 'do swim', ],
'correct_option' : 'do swim',
'topics' : ['does happen',]},
{'question_string' : 'My friend ______ every Saturday, I am sure.', 
'options' : ['do work', 'was not works', 'are not working', 'is not work', 'does work', ],
'correct_option' : 'does work',
'topics' : ['does happen',]},
{'question_string' : 'My friend and I ______ usually, I am sure.', 
'options' : ['are not sing', 'does sing', 'was not sing', 'do sing', 'was not singing', ],
'correct_option' : 'do sing',
'topics' : ['does happen',]},
{'question_string' : 'The girl ______ from time to time, I am sure.', 
'options' : ['was not swims', 'does swim', 'are not swimming', 'do swim', 'is not swim', ],
'correct_option' : 'does swim',
'topics' : ['does happen',]},
{'question_string' : 'Our children ______ every Saturday, I am sure.', 
'options' : ['was not drinking', 'do drink', 'was not drink', 'does drink', 'are not drink', ],
'correct_option' : 'do drink',
'topics' : ['does happen',]},
{'question_string' : 'She ______ frequently, I am sure.', 
'options' : ['do work', 'is not work', 'does work', 'are not working', 'was not works', ],
'correct_option' : 'does work',
'topics' : ['does happen',]},
{'question_string' : 'All of you ______ yam every weekend, I am sure.', 
'options' : ['does eat', 'was not eat', 'are not eat', 'do eat', 'was not eating', ],
'correct_option' : 'do eat',
'topics' : ['does happen',]},
{'question_string' : 'They ______ every Wednesday, I am sure.', 
'options' : ['does drink', 'do drink', 'was not drinking', 'was not drink', 'are not drink', ],
'correct_option' : 'do drink',
'topics' : ['does happen',]},
{'question_string' : 'You ______ groundnuts every weekend, I am sure.', 
'options' : ['does eat', 'was not eating', 'do eat', 'are not eat', 'was not eat', ],
'correct_option' : 'do eat',
'topics' : ['does happen',]},
{'question_string' : 'The boy ______ groundnuts repeatedly, I am sure.', 
'options' : ['does eat', 'are not eating', 'was not eats', 'do eat', 'is not eat', ],
'correct_option' : 'does eat',
'topics' : ['does happen',]},
{'question_string' : 'You ______ at all.', 
'options' : ['do not speak', 'are not speak', 'does not speak', 'was not speak', 'was not speaking', ],
'correct_option' : 'do not speak',
'topics' : ['does not happen',]},
{'question_string' : 'She ______ food at all.', 
'options' : ['does not eat', 'do not eat', 'are not eating', 'is not eat', 'was not eats', ],
'correct_option' : 'does not eat',
'topics' : ['does not happen',]},
{'question_string' : 'Many of you ______ at all.', 
'options' : ['do not drink', 'was not drink', 'was not drinking', 'does not drink', 'are not drink', ],
'correct_option' : 'do not drink',
'topics' : ['does not happen',]},
{'question_string' : 'Both of us ______ at any time.', 
'options' : ['are not sleep', 'does not sleep', 'do not sleep', 'was not sleep', 'was not sleeping', ],
'correct_option' : 'do not sleep',
'topics' : ['does not happen',]},
{'question_string' : 'I ______ popcorn at any time.', 
'options' : ['am not eat', 'are not eating', 'does not eat', 'do not eat', 'was not eat', ],
'correct_option' : 'do not eat',
'topics' : ['does not happen',]},
{'question_string' : 'All of us ______ at all.', 
'options' : ['was not working', 'does not work', 'was not work', 'do not work', 'are not work', ],
'correct_option' : 'do not work',
'topics' : ['does not happen',]},
{'question_string' : 'My friend ______ at all.', 
'options' : ['are not swimming', 'does not swim', 'do not swim', 'is not swim', 'was not swims', ],
'correct_option' : 'does not swim',
'topics' : ['does not happen',]},
{'question_string' : 'My friend and I ______ popcorn at any time.', 
'options' : ['was not eat', 'does not eat', 'do not eat', 'are not eat', 'was not eating', ],
'correct_option' : 'do not eat',
'topics' : ['does not happen',]},
{'question_string' : 'Many of you ______ at any time.', 
'options' : ['does not work', 'are not work', 'do not work', 'was not work', 'was not working', ],
'correct_option' : 'do not work',
'topics' : ['does not happen',]},
{'question_string' : 'I ______ at any time.', 
'options' : ['do not speak', 'are not speaking', 'was not speak', 'am not speak', 'does not speak', ],
'correct_option' : 'do not speak',
'topics' : ['does not happen',]},
{'question_string' : 'The girl ______ popcorn at all.', 
'options' : ['is not eat', 'do not eat', 'was not eats', 'does not eat', 'are not eating', ],
'correct_option' : 'does not eat',
'topics' : ['does not happen',]},
{'question_string' : 'You ______ at any time.', 
'options' : ['are not sing', 'was not singing', 'do not sing', 'was not sing', 'does not sing', ],
'correct_option' : 'do not sing',
'topics' : ['does not happen',]},
{'question_string' : 'You ______ at any time.', 
'options' : ['was not sing', 'do not sing', 'was not singing', 'are not sing', 'does not sing', ],
'correct_option' : 'do not sing',
'topics' : ['does not happen',]},
{'question_string' : 'All of us ______ at any time.', 
'options' : ['do not swim', 'was not swim', 'does not swim', 'are not swim', 'was not swimming', ],
'correct_option' : 'do not swim',
'topics' : ['does not happen',]},
{'question_string' : 'That child ______ at any time.', 
'options' : ['was not drinks', 'is not drink', 'are not drinking', 'does not drink', 'do not drink', ],
'correct_option' : 'does not drink',
'topics' : ['does not happen',]},
{'question_string' : 'Many of you ______ at all.', 
'options' : ['was not speaking', 'does not speak', 'do not speak', 'was not speak', 'are not speak', ],
'correct_option' : 'do not speak',
'topics' : ['does not happen',]},
{'question_string' : 'You ______ at any time.', 
'options' : ['are not swim', 'was not swim', 'do not swim', 'was not swimming', 'does not swim', ],
'correct_option' : 'do not swim',
'topics' : ['does not happen',]},
{'question_string' : 'You ______ at all.', 
'options' : ['was not sing', 'does not sing', 'are not sing', 'do not sing', 'was not singing', ],
'correct_option' : 'do not sing',
'topics' : ['does not happen',]},
{'question_string' : 'I ______ at all.', 
'options' : ['am not work', 'do not work', 'are not working', 'does not work', 'was not work', ],
'correct_option' : 'do not work',
'topics' : ['does not happen',]},
{'question_string' : 'You ______ at any time.', 
'options' : ['are not sing', 'does not sing', 'do not sing', 'was not singing', 'was not sing', ],
'correct_option' : 'do not sing',
'topics' : ['does not happen',]},
{'question_string' : 'You ______ at any time.', 
'options' : ['was not swimming', 'do not swim', 'was not swim', 'are not swim', 'does not swim', ],
'correct_option' : 'do not swim',
'topics' : ['does not happen',]},
{'question_string' : 'I ______ at any time.', 
'options' : ['was not drink', 'are not drinking', 'does not drink', 'am not drink', 'do not drink', ],
'correct_option' : 'do not drink',
'topics' : ['does not happen',]},
{'question_string' : 'The boy ______ at all.', 
'options' : ['does not drink', 'was not drinks', 'is not drink', 'are not drinking', 'do not drink', ],
'correct_option' : 'does not drink',
'topics' : ['does not happen',]},
{'question_string' : 'He ______ at any time.', 
'options' : ['does not sing', 'is not sing', 'are not singing', 'do not sing', 'was not sings', ],
'correct_option' : 'does not sing',
'topics' : ['does not happen',]},
{'question_string' : 'You ______ at all.', 
'options' : ['do not swim', 'are not swim', 'does not swim', 'was not swim', 'was not swimming', ],
'correct_option' : 'do not swim',
'topics' : ['does not happen',]},
{'question_string' : '______ eat groundnuts often.', 
'options' : ['She', 'The girl', 'The boy', 'That child', 'I', ],
'correct_option' : 'I',
'topics' : ['happens',]},
{'question_string' : '______ swims every Wednesday.', 
'options' : ['We', 'You', 'Our children', 'Both of you', 'She', ],
'correct_option' : 'She',
'topics' : ['happens',]},
{'question_string' : '______ work on Mondays.', 
'options' : ['She', 'That child', 'My friend and I', 'The girl', 'He', ],
'correct_option' : 'My friend and I',
'topics' : ['happens',]},
{'question_string' : '______ sing every week.', 
'options' : ['The boy', 'That child', 'We', 'The girl', 'He', ],
'correct_option' : 'We',
'topics' : ['happens',]},
{'question_string' : '______ swims often.', 
'options' : ['I', 'You', 'My friend and I', 'My parents', 'That child', ],
'correct_option' : 'That child',
'topics' : ['happens',]},
{'question_string' : '______ eat bread again and again.', 
'options' : ['She', 'That child', 'The girl', 'You and I', 'My friend', ],
'correct_option' : 'You and I',
'topics' : ['happens',]},
{'question_string' : '______ speak daily.', 
'options' : ['That child', 'He', 'All of you', 'My friend', 'She', ],
'correct_option' : 'All of you',
'topics' : ['happens',]},
{'question_string' : '______ swims all the time.', 
'options' : ['Our children', 'I', 'She', 'Both of you', 'You', ],
'correct_option' : 'She',
'topics' : ['happens',]},
{'question_string' : '______ sing every weekend.', 
'options' : ['He', 'The boy', 'My friend', 'All of you', 'She', ],
'correct_option' : 'All of you',
'topics' : ['happens',]},
{'question_string' : '______ drinks usually.', 
'options' : ['My friends', 'You', 'She', 'I', 'Many of you', ],
'correct_option' : 'She',
'topics' : ['happens',]},
{'question_string' : '______ works every Wednesday.', 
'options' : ['I', 'That child', 'Both of you', 'My parents', 'You and I', ],
'correct_option' : 'That child',
'topics' : ['happens',]},
{'question_string' : '______ sleeps every day.', 
'options' : ['They', 'Both of you', 'The boy', 'You', 'All of us', ],
'correct_option' : 'The boy',
'topics' : ['happens',]},
{'question_string' : '______ eats popcorn on weekends.', 
'options' : ['Some of us', 'She', 'Our children', 'You', 'I', ],
'correct_option' : 'She',
'topics' : ['happens',]},
{'question_string' : '______ eat food all the time.', 
'options' : ['The girl', 'He', 'She', 'All of you', 'My friend', ],
'correct_option' : 'All of you',
'topics' : ['happens',]},
{'question_string' : '______ swim every week.', 
'options' : ['Both of us', 'He', 'That child', 'The boy', 'The girl', ],
'correct_option' : 'Both of us',
'topics' : ['happens',]},
{'question_string' : '______ sing every day.', 
'options' : ['The boy', 'You', 'My friend', 'She', 'That child', ],
'correct_option' : 'You',
'topics' : ['happens',]},
{'question_string' : '______ work often.', 
'options' : ['That child', 'She', 'He', 'The boy', 'I', ],
'correct_option' : 'I',
'topics' : ['happens',]},
{'question_string' : '______ sleeps on weekends.', 
'options' : ['You', 'That child', 'Many of you', 'I', 'My parents', ],
'correct_option' : 'That child',
'topics' : ['happens',]},
{'question_string' : '______ drinks all the time.', 
'options' : ['My friend and I', 'My friend', 'You', 'I', 'They', ],
'correct_option' : 'My friend',
'topics' : ['happens',]},
{'question_string' : '______ sing again and again.', 
'options' : ['She', 'He', 'That child', 'My parents', 'The boy', ],
'correct_option' : 'My parents',
'topics' : ['happens',]},
{'question_string' : '______ sing all the time.', 
'options' : ['That child', 'My friend', 'She', 'He', 'I', ],
'correct_option' : 'I',
'topics' : ['happens',]},
{'question_string' : '______ sleep from time to time.', 
'options' : ['That child', 'The boy', 'My friend', 'They', 'He', ],
'correct_option' : 'They',
'topics' : ['happens',]},
{'question_string' : '______ work repeatedly.', 
'options' : ['The boy', 'She', 'We', 'That child', 'He', ],
'correct_option' : 'We',
'topics' : ['happens',]},
{'question_string' : '______ sleeps every weekend.', 
'options' : ['All of us', 'I', 'You', 'Some of you', 'The girl', ],
'correct_option' : 'The girl',
'topics' : ['happens',]},
{'question_string' : '______ sleeps frequently.', 
'options' : ['Some of you', 'I', 'He', 'You', 'Both of us', ],
'correct_option' : 'He',
'topics' : ['happens',]},
{'question_string' : '______ sing every Wednesday.', 
'options' : ['The girl', 'That child', 'Both of us', 'He', 'The boy', ],
'correct_option' : 'Both of us',
'topics' : ['happens',]},
{'question_string' : '______ sings again and again.', 
'options' : ['You and I', 'You', 'That child', 'Our children', 'I', ],
'correct_option' : 'That child',
'topics' : ['happens',]},
{'question_string' : '______ sings on weekends.', 
'options' : ['The boy', 'You and I', 'The students', 'You', 'I', ],
'correct_option' : 'The boy',
'topics' : ['happens',]},
{'question_string' : '______ sleep every day.', 
'options' : ['The girl', 'The boy', 'She', 'You', 'That child', ],
'correct_option' : 'You',
'topics' : ['happens',]},
{'question_string' : '______ drinks every time.', 
'options' : ['I', 'Both of you', 'You', 'My friend and I', 'My friend', ],
'correct_option' : 'My friend',
'topics' : ['happens',]},
{'question_string' : '______ sing often.', 
'options' : ['My friend', 'She', 'I', 'He', 'That child', ],
'correct_option' : 'I',
'topics' : ['happens',]},
{'question_string' : '______ sings every time.', 
'options' : ['My parents', 'You', 'I', 'She', 'You', ],
'correct_option' : 'She',
'topics' : ['happens',]},
{'question_string' : '______ speaks on Sundays.', 
'options' : ['I', 'The boy', 'My friends', 'You and I', 'You', ],
'correct_option' : 'The boy',
'topics' : ['happens',]},
{'question_string' : '______ speaks all the time.', 
'options' : ['That child', 'You', 'Both of us', 'Some of you', 'I', ],
'correct_option' : 'That child',
'topics' : ['happens',]},
{'question_string' : '______ eats popcorn every weekend.', 
'options' : ['Our children', 'The boy', 'I', 'You', 'Many of you', ],
'correct_option' : 'The boy',
'topics' : ['happens',]},
{'question_string' : '______ speak usually.', 
'options' : ['She', 'The girl', 'My friend', 'He', 'You', ],
'correct_option' : 'You',
'topics' : ['happens',]},
{'question_string' : '______ sing again and again.', 
'options' : ['She', 'The boy', 'The girl', 'You', 'He', ],
'correct_option' : 'You',
'topics' : ['happens',]},
{'question_string' : '______ eat food on Sundays.', 
'options' : ['All of us', 'My friend', 'That child', 'He', 'The girl', ],
'correct_option' : 'All of us',
'topics' : ['happens',]},
{'question_string' : '______ works daily.', 
'options' : ['Many of you', 'All of us', 'The boy', 'I', 'You', ],
'correct_option' : 'The boy',
'topics' : ['happens',]},
{'question_string' : '______ drinks on weekends.', 
'options' : ['The girl', 'Both of you', 'I', 'You', 'We', ],
'correct_option' : 'The girl',
'topics' : ['happens',]},
{'question_string' : '______ works daily.', 
'options' : ['That child', 'You', 'I', 'They', 'You', ],
'correct_option' : 'That child',
'topics' : ['happens',]},
{'question_string' : '______ eats groundnuts on weekends.', 
'options' : ['Some of us', 'You', 'I', 'The students', 'That child', ],
'correct_option' : 'That child',
'topics' : ['happens',]},
{'question_string' : '______ swims again and again.', 
'options' : ['I', 'You', 'The students', 'My friend', 'All of us', ],
'correct_option' : 'My friend',
'topics' : ['happens',]},
{'question_string' : '______ speak every Wednesday.', 
'options' : ['She', 'All of us', 'The boy', 'He', 'My friend', ],
'correct_option' : 'All of us',
'topics' : ['happens',]},
{'question_string' : '______ eat rice on weekends.', 
'options' : ['The boy', 'The girl', 'He', 'You', 'That child', ],
'correct_option' : 'You',
'topics' : ['happens',]},
{'question_string' : '______ swim on Mondays.', 
'options' : ['You', 'She', 'That child', 'My friend', 'The boy', ],
'correct_option' : 'You',
'topics' : ['happens',]},
{'question_string' : '______ drinks on Mondays.', 
'options' : ['I', 'My friends', 'That child', 'Some of you', 'You', ],
'correct_option' : 'That child',
'topics' : ['happens',]},
{'question_string' : '______ sings from time to time.', 
'options' : ['She', 'I', 'Our children', 'You and I', 'You', ],
'correct_option' : 'She',
'topics' : ['happens',]},
{'question_string' : '______ speaks every now and then.', 
'options' : ['Some of you', 'I', 'The girl', 'Our children', 'We', ],
'correct_option' : 'The girl',
'topics' : ['happens',]},
{'question_string' : '______ swims often.', 
'options' : ['You', 'That child', 'Both of us', 'My friends', 'I', ],
'correct_option' : 'That child',
'topics' : ['happens',]},
{'question_string' : '______ sleep all the time.', 
'options' : ['He', 'That child', 'The girl', 'The boy', 'Many of you', ],
'correct_option' : 'Many of you',
'topics' : ['happens',]},
{'question_string' : '______ sing usually.', 
'options' : ['She', 'The boy', 'My friend', 'That child', 'We', ],
'correct_option' : 'We',
'topics' : ['happens',]},
{'question_string' : '______ work usually.', 
'options' : ['She', 'The girl', 'That child', 'My friend', 'You', ],
'correct_option' : 'You',
'topics' : ['happens',]},
{'question_string' : '______ drink every time.', 
'options' : ['My friend', 'The boy', 'The students', 'That child', 'The girl', ],
'correct_option' : 'The students',
'topics' : ['happens',]},
{'question_string' : '______ sings all the time.', 
'options' : ['Many of you', 'The girl', 'You', 'We', 'My friends', ],
'correct_option' : 'The girl',
'topics' : ['happens',]},
{'question_string' : '______ drink usually.', 
'options' : ['The girl', 'She', 'You', 'My friend', 'He', ],
'correct_option' : 'You',
'topics' : ['happens',]},
{'question_string' : '______ swim on weekends.', 
'options' : ['The boy', 'The girl', 'We', 'He', 'She', ],
'correct_option' : 'We',
'topics' : ['happens',]},
{'question_string' : '______ eats bread often.', 
'options' : ['My friends', 'You', 'I', 'All of you', 'He', ],
'correct_option' : 'He',
'topics' : ['happens',]},
{'question_string' : '______ drink every week.', 
'options' : ['My friend', 'The boy', 'They', 'The girl', 'He', ],
'correct_option' : 'They',
'topics' : ['happens',]},
{'question_string' : '______ sleep every week.', 
'options' : ['She', 'That child', 'You', 'The boy', 'He', ],
'correct_option' : 'You',
'topics' : ['happens',]},
{'question_string' : '______ speak every weekend.', 
'options' : ['She', 'The boy', 'The girl', 'That child', 'You', ],
'correct_option' : 'You',
'topics' : ['happens',]},
{'question_string' : '______ works every week.', 
'options' : ['They', 'You', 'I', 'That child', 'We', ],
'correct_option' : 'That child',
'topics' : ['happens',]},
{'question_string' : '______ eats yam daily.', 
'options' : ['My friend and I', 'My friend', 'I', 'Both of you', 'You', ],
'correct_option' : 'My friend',
'topics' : ['happens',]},
{'question_string' : '______ eats popcorn often.', 
'options' : ['I', 'Many of you', 'The girl', 'They', 'You', ],
'correct_option' : 'The girl',
'topics' : ['happens',]},
{'question_string' : '______ sleeps every week.', 
'options' : ['Many of you', 'My friend and I', 'I', 'The girl', 'My friends', ],
'correct_option' : 'The girl',
'topics' : ['happens',]},
{'question_string' : '______ work again and again.', 
'options' : ['My parents', 'That child', 'She', 'The boy', 'He', ],
'correct_option' : 'My parents',
'topics' : ['happens',]},
{'question_string' : '______ drinks on weekends.', 
'options' : ['My friend', 'Many of you', 'You and I', 'I', 'You', ],
'correct_option' : 'My friend',
'topics' : ['happens',]},
{'question_string' : '______ sing all the time.', 
'options' : ['The girl', 'The boy', 'He', 'She', 'You', ],
'correct_option' : 'You',
'topics' : ['happens',]},
{'question_string' : '______ drinks again and again.', 
'options' : ['I', 'You', 'The girl', 'Many of you', 'My parents', ],
'correct_option' : 'The girl',
'topics' : ['happens',]},
{'question_string' : '______ swim every time.', 
'options' : ['He', 'My friend', 'She', 'Some of us', 'The boy', ],
'correct_option' : 'Some of us',
'topics' : ['happens',]},
{'question_string' : '______ speaks on weekends.', 
'options' : ['You', 'My parents', 'She', 'All of us', 'Many of you', ],
'correct_option' : 'She',
'topics' : ['happens',]},
{'question_string' : '______ sleep every week.', 
'options' : ['That child', 'Both of us', 'He', 'The boy', 'My friend', ],
'correct_option' : 'Both of us',
'topics' : ['happens',]},
{'question_string' : '______ drinks daily.', 
'options' : ['Some of us', 'You', 'Many of you', 'That child', 'My parents', ],
'correct_option' : 'That child',
'topics' : ['happens',]},
{'question_string' : '______ speaks every weekend.', 
'options' : ['The girl', 'Many of you', 'I', 'My friends', 'You', ],
'correct_option' : 'The girl',
'topics' : ['happens',]},
{'question_string' : '______ speaks every now and then.', 
'options' : ['The girl', 'They', 'Many of you', 'I', 'My friend and I', ],
'correct_option' : 'The girl',
'topics' : ['happens',]},
{'question_string' : '______ does sing on Mondays, I am very sure.', 
'options' : ['You', 'The girl', 'Some of you', 'I', 'Both of us', ],
'correct_option' : 'The girl',
'topics' : ['does happen',]},
{'question_string' : '______ do speak repeatedly, I am very sure.', 
'options' : ['He', 'The girl', 'The students', 'The boy', 'That child', ],
'correct_option' : 'The students',
'topics' : ['does happen',]},
{'question_string' : '______ does sing often, I am very sure.', 
'options' : ['Many of you', 'I', 'Our children', 'My friend', 'You', ],
'correct_option' : 'My friend',
'topics' : ['does happen',]},
{'question_string' : '______ do drink daily, I am very sure.', 
'options' : ['She', 'I', 'My friend', 'The boy', 'That child', ],
'correct_option' : 'I',
'topics' : ['does happen',]},
{'question_string' : '______ do work all the time, I am very sure.', 
'options' : ['He', 'My friends', 'My friend', 'That child', 'The boy', ],
'correct_option' : 'My friends',
'topics' : ['does happen',]},
{'question_string' : '______ does swim on Mondays, I am very sure.', 
'options' : ['All of us', 'Many of you', 'My friend', 'I', 'They', ],
'correct_option' : 'My friend',
'topics' : ['does happen',]},
{'question_string' : '______ do speak again and again, I am very sure.', 
'options' : ['The girl', 'We', 'He', 'The boy', 'She', ],
'correct_option' : 'We',
'topics' : ['does happen',]},
{'question_string' : '______ do work every day, I am very sure.', 
'options' : ['He', 'I', 'The girl', 'My friend', 'That child', ],
'correct_option' : 'I',
'topics' : ['does happen',]},
{'question_string' : '______ does swim every Saturday, I am very sure.', 
'options' : ['I', 'Many of you', 'You', 'My friend', 'We', ],
'correct_option' : 'My friend',
'topics' : ['does happen',]},
{'question_string' : '______ does sleep on weekends, I am very sure.', 
'options' : ['I', 'All of you', 'My parents', 'The girl', 'My friend and I', ],
'correct_option' : 'The girl',
'topics' : ['does happen',]},
{'question_string' : '______ do sing all the time, I am very sure.', 
'options' : ['That child', 'He', 'She', 'I', 'The boy', ],
'correct_option' : 'I',
'topics' : ['does happen',]},
{'question_string' : '______ do work on Sundays, I am very sure.', 
'options' : ['The boy', 'He', 'The girl', 'My friend', 'Our children', ],
'correct_option' : 'Our children',
'topics' : ['does happen',]},
{'question_string' : '______ does speak every day, I am very sure.', 
'options' : ['Both of you', 'All of us', 'You', 'My friend', 'Our children', ],
'correct_option' : 'My friend',
'topics' : ['does happen',]},
{'question_string' : '______ do sleep daily, I am very sure.', 
'options' : ['The boy', 'Our children', 'My friend', 'She', 'That child', ],
'correct_option' : 'Our children',
'topics' : ['does happen',]},
{'question_string' : '______ do drink on Mondays, I am very sure.', 
'options' : ['She', 'That child', 'The girl', 'The boy', 'You', ],
'correct_option' : 'You',
'topics' : ['does happen',]},
{'question_string' : '______ does sing every Saturday, I am very sure.', 
'options' : ['They', 'All of you', 'My friend', 'You', 'Some of us', ],
'correct_option' : 'My friend',
'topics' : ['does happen',]},
{'question_string' : '______ do sleep every now and then, I am very sure.', 
'options' : ['The girl', 'The boy', 'Some of you', 'My friend', 'That child', ],
'correct_option' : 'Some of you',
'topics' : ['does happen',]},
{'question_string' : '______ does swim all the time, I am very sure.', 
'options' : ['I', 'Many of you', 'The students', 'You', 'That child', ],
'correct_option' : 'That child',
'topics' : ['does happen',]},
{'question_string' : '______ does sleep on Mondays, I am very sure.', 
'options' : ['I', 'My friend', 'You', 'My parents', 'You and I', ],
'correct_option' : 'My friend',
'topics' : ['does happen',]},
{'question_string' : '______ does eat food every time, I am very sure.', 
'options' : ['My parents', 'You', 'I', 'Both of us', 'The girl', ],
'correct_option' : 'The girl',
'topics' : ['does happen',]},
{'question_string' : '______ do drink all the time, I am very sure.', 
'options' : ['The girl', 'She', 'That child', 'The boy', 'Both of us', ],
'correct_option' : 'Both of us',
'topics' : ['does happen',]},
{'question_string' : '______ do swim every now and then, I am very sure.', 
'options' : ['Our children', 'The boy', 'She', 'That child', 'My friend', ],
'correct_option' : 'Our children',
'topics' : ['does happen',]},
{'question_string' : '______ do drink every weekend, I am very sure.', 
'options' : ['He', 'My friend', 'I', 'That child', 'The girl', ],
'correct_option' : 'I',
'topics' : ['does happen',]},
{'question_string' : '______ do work from time to time, I am very sure.', 
'options' : ['He', 'My friend', 'The boy', 'My friends', 'That child', ],
'correct_option' : 'My friends',
'topics' : ['does happen',]},
{'question_string' : '______ do speak on Sundays, I am very sure.', 
'options' : ['My friend', 'She', 'That child', 'My parents', 'The boy', ],
'correct_option' : 'My parents',
'topics' : ['does happen',]},
{'question_string' : '______ do not speak at any time.', 
'options' : ['You', 'That child', 'She', 'My friend', 'The girl', ],
'correct_option' : 'You',
'topics' : ['does not happen',]},
{'question_string' : '______ do not swim at all.', 
'options' : ['She', 'You', 'My friend', 'The girl', 'The boy', ],
'correct_option' : 'You',
'topics' : ['does not happen',]},
{'question_string' : '______ do not work at all.', 
'options' : ['My friend', 'That child', 'She', 'The girl', 'They', ],
'correct_option' : 'They',
'topics' : ['does not happen',]},
{'question_string' : '______ do not sleep at all.', 
'options' : ['The boy', 'My friend', 'I', 'That child', 'The girl', ],
'correct_option' : 'I',
'topics' : ['does not happen',]},
{'question_string' : '______ does not sleep at all.', 
'options' : ['We', 'You', 'You', 'The boy', 'I', ],
'correct_option' : 'The boy',
'topics' : ['does not happen',]},
{'question_string' : '______ do not drink at all.', 
'options' : ['Both of us', 'The girl', 'My friend', 'She', 'He', ],
'correct_option' : 'Both of us',
'topics' : ['does not happen',]},
{'question_string' : '______ do not work at any time.', 
'options' : ['My friend', 'My friend and I', 'She', 'The boy', 'The girl', ],
'correct_option' : 'My friend and I',
'topics' : ['does not happen',]},
{'question_string' : '______ does not work at any time.', 
'options' : ['All of you', 'All of us', 'That child', 'I', 'You', ],
'correct_option' : 'That child',
'topics' : ['does not happen',]},
{'question_string' : '______ does not speak at all.', 
'options' : ['You', 'My friends', 'That child', 'I', 'You', ],
'correct_option' : 'That child',
'topics' : ['does not happen',]},
{'question_string' : '______ do not drink at all.', 
'options' : ['He', 'Both of us', 'She', 'My friend', 'That child', ],
'correct_option' : 'Both of us',
'topics' : ['does not happen',]},
{'question_string' : '______ do not swim at all.', 
'options' : ['That child', 'You', 'The boy', 'She', 'He', ],
'correct_option' : 'You',
'topics' : ['does not happen',]},
{'question_string' : '______ do not sing at all.', 
'options' : ['The boy', 'He', 'I', 'That child', 'The girl', ],
'correct_option' : 'I',
'topics' : ['does not happen',]},
{'question_string' : '______ do not speak at any time.', 
'options' : ['You', 'The boy', 'She', 'He', 'The girl', ],
'correct_option' : 'You',
'topics' : ['does not happen',]},
{'question_string' : '______ do not sing at any time.', 
'options' : ['You', 'The girl', 'He', 'That child', 'The boy', ],
'correct_option' : 'You',
'topics' : ['does not happen',]},
{'question_string' : '______ do not swim at any time.', 
'options' : ['Our children', 'He', 'That child', 'She', 'The girl', ],
'correct_option' : 'Our children',
'topics' : ['does not happen',]},
{'question_string' : '______ does not drink at any time.', 
'options' : ['That child', 'Many of you', 'All of us', 'I', 'You', ],
'correct_option' : 'That child',
'topics' : ['does not happen',]},
{'question_string' : '______ does not drink at any time.', 
'options' : ['My parents', 'That child', 'I', 'You', 'All of us', ],
'correct_option' : 'That child',
'topics' : ['does not happen',]},
{'question_string' : '______ do not swim at any time.', 
'options' : ['She', 'He', 'The boy', 'The girl', 'You', ],
'correct_option' : 'You',
'topics' : ['does not happen',]},
{'question_string' : '______ do not speak at any time.', 
'options' : ['You', 'My friend', 'The boy', 'The girl', 'She', ],
'correct_option' : 'You',
'topics' : ['does not happen',]},
{'question_string' : '______ do not drink at any time.', 
'options' : ['My friend', 'That child', 'Some of you', 'She', 'He', ],
'correct_option' : 'Some of you',
'topics' : ['does not happen',]},
{'question_string' : '______ does not drink at any time.', 
'options' : ['We', 'I', 'He', 'You', 'Many of you', ],
'correct_option' : 'He',
'topics' : ['does not happen',]},
{'question_string' : '______ do not work at any time.', 
'options' : ['The students', 'The girl', 'He', 'She', 'The boy', ],
'correct_option' : 'The students',
'topics' : ['does not happen',]},
{'question_string' : '______ does not sing at all.', 
'options' : ['The boy', 'Many of you', 'The students', 'You', 'I', ],
'correct_option' : 'The boy',
'topics' : ['does not happen',]},
{'question_string' : '______ does not sleep at all.', 
'options' : ['He', 'Both of us', 'I', 'You', 'They', ],
'correct_option' : 'He',
'topics' : ['does not happen',]},
{'question_string' : '______ do not sleep at all.', 
'options' : ['Some of us', 'My friend', 'That child', 'She', 'The boy', ],
'correct_option' : 'Some of us',
'topics' : ['does not happen',]},

    ]


basic_science = []
    
